In [1]:

import numpy as np
# Входной вектор
x = np.array([1.0, 0.0, 2.0, -1.0, 0.5])
print("Входной вектор x:", x)
print("Размерность входа:", x.shape)

Входной вектор x: [ 1.   0.   2.  -1.   0.5]
Размерность входа: (5,)


In [2]:

W1 = np.array([
    [0.2, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.2, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.2, -0.1, 0.0]
])
b1 = np.array([0.0, 0.0, 0.0])

W2 = np.array([
    [0.1, 0.0, 0.0],
    [0.0, 0.1, 1.0]
])
b2 = np.array([0.0, 0.0])

W3 = np.array([[0.1, 0.1]])
b3 = np.array([0.0])

W_out_1layer = np.array([[0.3, -0.2, 0.1]])
b_out_1layer = np.array([0.0])

print("W1 (5x3):\n", W1)
print("\nW2 (3x2):\n", W2)
print("\nW3 (2x1):\n", W3)

W1 (5x3):
 [[ 0.2  0.   0.   0.   0. ]
 [ 0.   0.2  0.   0.   0. ]
 [ 0.   0.   0.2 -0.1  0. ]]

W2 (3x2):
 [[0.1 0.  0. ]
 [0.  0.1 1. ]]

W3 (2x1):
 [[0.1 0.1]]


In [3]:

def relu(z):
    """ReLU activation"""
    return np.maximum(0, z)

def sigmoid(z):
    """Sigmoid activation"""
    return 1 / (1 + np.exp(-z))

def tanh_activation(z):
    """Tanh activation"""
    return np.tanh(z)

def softmax(z):
    """Softmax activation (для многоклассового выхода)"""
    exp_z = np.exp(z - np.max(z))
    return exp_z / np.sum(exp_z)
# Проверка функций
print("Проверка функций активации:")
print(f"ReLU(-2) = {relu(-2)}")
print(f"Sigmoid(0) = {sigmoid(0)}")
print(f"Tanh(0.5) = {tanh_activation(0.5)}")
print(f"Softmax([1, 2, 3]) = {softmax(np.array([1, 2, 3]))}")

Проверка функций активации:
ReLU(-2) = 0
Sigmoid(0) = 0.5
Tanh(0.5) = 0.46211715726000974
Softmax([1, 2, 3]) = [0.09003057 0.24472847 0.66524096]


In [4]:

print("=" * 70)
print("1. СЕТЬ С ОДНИМ СКРЫТЫМ СЛОЕМ (5 → 3 → 1)")
print("=" * 70)
print("Активации: скрытый слой - tanh, выходной слой - sigmoid\n")

print("--- Шаг 1: Скрытый слой (tanh) ---")
z1 = W1 @ x + b1
print(f"z(1) = {z1}")
print(f"z(1) вычислено: z1 = {z1[0]:.4f}, z2 = {z1[1]:.4f}, z3 = {z1[2]:.4f}")

a1 = tanh_activation(z1)
print(f"a(1) = tanh(z(1)) = {a1}")
print(f"a(1) округленно: a1 = {a1[0]:.4f}, a2 = {a1[1]:.4f}, a3 = {a1[2]:.4f}")

print("\n--- Шаг 2: Выходной слой (sigmoid) ---")
z2 = W_out_1layer @ a1 + b_out_1layer
print(f"z(2) = {z2[0]:.6f}")
print(f"z(2) = 0.3*{a1[0]:.4f} + (-0.2)*{a1[1]:.4f} + 0.1*{a1[2]:.4f} = {z2[0]:.6f}")

a2 = sigmoid(z2)
print(f"a(2) = sigmoid(z(2)) = {a2[0]:.6f}")

print(f"\n>>> ВЫХОД СЕТИ: y_hat = {a2[0]:.6f}")

1. СЕТЬ С ОДНИМ СКРЫТЫМ СЛОЕМ (5 → 3 → 1)
Активации: скрытый слой - tanh, выходной слой - sigmoid

--- Шаг 1: Скрытый слой (tanh) ---
z(1) = [0.2 0.  0.5]
z(1) вычислено: z1 = 0.2000, z2 = 0.0000, z3 = 0.5000
a(1) = tanh(z(1)) = [0.19737532 0.         0.46211716]
a(1) округленно: a1 = 0.1974, a2 = 0.0000, a3 = 0.4621

--- Шаг 2: Выходной слой (sigmoid) ---
z(2) = 0.105424
z(2) = 0.3*0.1974 + (-0.2)*0.0000 + 0.1*0.4621 = 0.105424
a(2) = sigmoid(z(2)) = 0.526332

>>> ВЫХОД СЕТИ: y_hat = 0.526332


In [5]:

print("=" * 70)
print("2. СЕТЬ С ДВУМЯ СКРЫТЫМИ СЛОЯМИ (5 → 3 → 2 → 1)")
print("=" * 70)
print("Активации: слой1 - tanh, слой2 - ReLU, выходной слой - sigmoid\n")

print("--- Шаг 1: Первый скрытый слой (tanh) ---")
z1_2 = W1 @ x + b1
print(f"z(1) = {z1_2}")
a1_2 = tanh_activation(z1_2)
print(f"a(1) = tanh(z(1)) = {a1_2}")

print("\n--- Шаг 2: Второй скрытый слой (ReLU) ---")
z2_2 = W2 @ a1_2 + b2
print(f"z(2) = {z2_2}")
print(f"z(2) вычислено:")
print(f"  Нейрон 1: 0.1*{a1_2[0]:.4f} + 0*{a1_2[1]:.4f} + 0*{a1_2[2]:.4f} = {z2_2[0]:.4f}")
print(f"  Нейрон 2: 0*{a1_2[0]:.4f} + 0.1*{a1_2[1]:.4f} + 1*{a1_2[2]:.4f} = {z2_2[1]:.4f}")

a2_2 = relu(z2_2)
print(f"a(2) = ReLU(z(2)) = {a2_2}")

print("\n--- Шаг 3: Выходной слой (sigmoid) ---")
z3_2 = W3 @ a2_2 + b3
print(f"z(3) = {z3_2[0]:.6f}")
print(f"z(3) = 0.1*{a2_2[0]:.4f} + 0.1*{a2_2[1]:.4f} = {z3_2[0]:.6f}")

a3_2 = sigmoid(z3_2)
print(f"a(3) = sigmoid(z(3)) = {a3_2[0]:.6f}")

print(f"\n>>> ВЫХОД СЕТИ: y_hat = {a3_2[0]:.6f}")

2. СЕТЬ С ДВУМЯ СКРЫТЫМИ СЛОЯМИ (5 → 3 → 2 → 1)
Активации: слой1 - tanh, слой2 - ReLU, выходной слой - sigmoid

--- Шаг 1: Первый скрытый слой (tanh) ---
z(1) = [0.2 0.  0.5]
a(1) = tanh(z(1)) = [0.19737532 0.         0.46211716]

--- Шаг 2: Второй скрытый слой (ReLU) ---
z(2) = [0.01973753 0.46211716]
z(2) вычислено:
  Нейрон 1: 0.1*0.1974 + 0*0.0000 + 0*0.4621 = 0.0197
  Нейрон 2: 0*0.1974 + 0.1*0.0000 + 1*0.4621 = 0.4621
a(2) = ReLU(z(2)) = [0.01973753 0.46211716]

--- Шаг 3: Выходной слой (sigmoid) ---
z(3) = 0.048185
z(3) = 0.1*0.0197 + 0.1*0.4621 = 0.048185
a(3) = sigmoid(z(3)) = 0.512044

>>> ВЫХОД СЕТИ: y_hat = 0.512044


In [6]:

print("=" * 70)
print("Добавляем веса для сети с тремя скрытыми слоями")
print("=" * 70)

W3_hidden = np.array([
    [0.2, 0.1],
    [0.1, 0.2],
    [0.15, 0.05]
])
b3_hidden = np.array([0.0, 0.0, 0.0])

W4_out = np.array([
    [0.2, 0.1, 0.15],
    [0.1, 0.2, 0.05]
])
b4_out = np.array([0.0, 0.0])

print("W3_hidden (2x3):\n", W3_hidden)
print("\nW4_out (3x2):\n", W4_out)

Добавляем веса для сети с тремя скрытыми слоями
W3_hidden (2x3):
 [[0.2  0.1 ]
 [0.1  0.2 ]
 [0.15 0.05]]

W4_out (3x2):
 [[0.2  0.1  0.15]
 [0.1  0.2  0.05]]


In [7]:

print("=" * 70)
print("3. СЕТЬ С ТРЕМЯ СКРЫТЫМИ СЛОЯМИ (5 → 3 → 2 → 3 → 2)")
print("=" * 70)
print("Активации: слой1 - tanh, слой2 - tanh, слой3 - ReLU, выходной слой - softmax\n")

print("--- Шаг 1: Первый скрытый слой (tanh) ---")
z1_3 = W1 @ x + b1
print(f"z(1) = {z1_3}")
a1_3 = tanh_activation(z1_3)
print(f"a(1) = tanh(z(1)) = {a1_3}")

print("\n--- Шаг 2: Второй скрытый слой (tanh) ---")
z2_3 = W2 @ a1_3 + b2
print(f"z(2) = {z2_3}")
a2_3 = tanh_activation(z2_3)
print(f"a(2) = tanh(z(2)) = {a2_3}")

print("\n--- Шаг 3: Третий скрытый слой (ReLU) ---")
z3_3 = W3_hidden @ a2_3 + b3_hidden
print(f"z(3) = {z3_3}")
print(f"z(3) вычислено:")
print(f"  Нейрон 1: 0.2*{a2_3[0]:.4f} + 0.1*{a2_3[1]:.4f} = {z3_3[0]:.4f}")
print(f"  Нейрон 2: 0.1*{a2_3[0]:.4f} + 0.2*{a2_3[1]:.4f} = {z3_3[1]:.4f}")
print(f"  Нейрон 3: 0.15*{a2_3[0]:.4f} + 0.05*{a2_3[1]:.4f} = {z3_3[2]:.4f}")

a3_3 = relu(z3_3)
print(f"a(3) = ReLU(z(3)) = {a3_3}")


print("\n--- Шаг 4: Выходной слой (softmax) ---")
z4_3 = W4_out @ a3_3 + b4_out
print(f"z(4) = {z4_3}")
print(f"z(4) вычислено:")
print(f"  Класс 0: 0.2*{a3_3[0]:.4f} + 0.1*{a3_3[1]:.4f} + 0.15*{a3_3[2]:.4f} = {z4_3[0]:.4f}")
print(f"  Класс 1: 0.1*{a3_3[0]:.4f} + 0.2*{a3_3[1]:.4f} + 0.05*{a3_3[2]:.4f} = {z4_3[1]:.4f}")

a4_3 = softmax(z4_3)
print(f"a(4) = softmax(z(4)) = {a4_3}")

print(f"\n>>> ВЫХОД СЕТИ (вероятности классов):")
print(f"    Класс 0: {a4_3[0]:.6f}")
print(f"    Класс 1: {a4_3[1]:.6f}")

3. СЕТЬ С ТРЕМЯ СКРЫТЫМИ СЛОЯМИ (5 → 3 → 2 → 3 → 2)
Активации: слой1 - tanh, слой2 - tanh, слой3 - ReLU, выходной слой - softmax

--- Шаг 1: Первый скрытый слой (tanh) ---
z(1) = [0.2 0.  0.5]
a(1) = tanh(z(1)) = [0.19737532 0.         0.46211716]

--- Шаг 2: Второй скрытый слой (tanh) ---
z(2) = [0.01973753 0.46211716]
a(2) = tanh(z(2)) = [0.01973497 0.43180818]

--- Шаг 3: Третий скрытый слой (ReLU) ---
z(3) = [0.04712781 0.08833513 0.02455065]
z(3) вычислено:
  Нейрон 1: 0.2*0.0197 + 0.1*0.4318 = 0.0471
  Нейрон 2: 0.1*0.0197 + 0.2*0.4318 = 0.0883
  Нейрон 3: 0.15*0.0197 + 0.05*0.4318 = 0.0246
a(3) = ReLU(z(3)) = [0.04712781 0.08833513 0.02455065]

--- Шаг 4: Выходной слой (softmax) ---
z(4) = [0.02194167 0.02360734]
z(4) вычислено:
  Класс 0: 0.2*0.0471 + 0.1*0.0883 + 0.15*0.0246 = 0.0219
  Класс 1: 0.1*0.0471 + 0.2*0.0883 + 0.05*0.0246 = 0.0236
a(4) = softmax(z(4)) = [0.49958358 0.50041642]

>>> ВЫХОД СЕТИ (вероятности классов):
    Класс 0: 0.499584
    Класс 1: 0.500416


In [8]:
# Ячейка 8: Сводная таблица результатов
print("=" * 70)
print("СВОДНАЯ ТАБЛИЦА РЕЗУЛЬТАТОВ")
print("=" * 70)

print("\n┌────────────────────────────────────────────┬────────────────────┐")
print("│ Конфигурация сети                          │ Выход сети         │")
print("├────────────────────────────────────────────┼────────────────────┤")

print(f"│ 1 скрытый слой (tanh → sigmoid)            │ y_hat = {a2[0]:.6f}    │")
print(f"│ 2 скрытых слоя (tanh → ReLU → sigmoid)     │ y_hat = {a3_2[0]:.6f}    │")

print("├────────────────────────────────────────────┼────────────────────┤")
print("│ 3 скрытых слоя (tanh → tanh → ReLU → softmax) │                    │")
print(f"│   - Вероятность класса 0                   │ {a4_3[0]:.6f}    │")
print(f"│   - Вероятность класса 1                   │ {a4_3[1]:.6f}    │")
print("└────────────────────────────────────────────┴────────────────────┘")

print("\n" + "=" * 70)
print("ПРОВЕРКА РАЗМЕРНОСТЕЙ")
print("=" * 70)
print(f"Вход x:              {x.shape}")
print(f"W1: {W1.shape} → z1: (3,) → a1: (3,)")
print(f"W2: {W2.shape} → z2: (2,) → a2: (2,)")
print(f"W3 (выходной для 2 слоёв): {W3.shape} → выход: (1,)")
print(f"W3_hidden: {W3_hidden.shape} → z3: (3,) → a3: (3,)")
print(f"W4_out: {W4_out.shape} → z4: (2,) → a4: (2,)")

СВОДНАЯ ТАБЛИЦА РЕЗУЛЬТАТОВ

┌────────────────────────────────────────────┬────────────────────┐
│ Конфигурация сети                          │ Выход сети         │
├────────────────────────────────────────────┼────────────────────┤
│ 1 скрытый слой (tanh → sigmoid)            │ y_hat = 0.526332    │
│ 2 скрытых слоя (tanh → ReLU → sigmoid)     │ y_hat = 0.512044    │
├────────────────────────────────────────────┼────────────────────┤
│ 3 скрытых слоя (tanh → tanh → ReLU → softmax) │                    │
│   - Вероятность класса 0                   │ 0.499584    │
│   - Вероятность класса 1                   │ 0.500416    │
└────────────────────────────────────────────┴────────────────────┘

ПРОВЕРКА РАЗМЕРНОСТЕЙ
Вход x:              (5,)
W1: (3, 5) → z1: (3,) → a1: (3,)
W2: (2, 3) → z2: (2,) → a2: (2,)
W3 (выходной для 2 слоёв): (1, 2) → выход: (1,)
W3_hidden: (3, 2) → z3: (3,) → a3: (3,)
W4_out: (2, 3) → z4: (2,) → a4: (2,)


In [9]:

print("=" * 70)
print("ДЕТАЛЬНЫЙ РАЗБОР ВЫЧИСЛЕНИЙ (для 2-х скрытых слоёв)")
print("=" * 70)

print("\n1. Вычисление первого скрытого слоя:")
print(f"   z1[0] = 0.2*1 + 0*0 + 0*2 + 0*(-1) + 0*0.5 = 0.2")
print(f"   z1[1] = 0*1 + 0.2*0 + 0*2 + 0*(-1) + 0*0.5 = 0.0")
print(f"   z1[2] = 0*1 + 0*0 + 0.2*2 + (-0.1)*(-1) + 0*0.5 = 0.4 + 0.1 = 0.5")
print(f"   a1 = tanh([0.2, 0, 0.5]) = [{tanh_activation(0.2):.4f}, 0, {tanh_activation(0.5):.4f}]")

print("\n2. Вычисление второго скрытого слоя:")
print(f"   z2[0] = 0.1*{a1_2[0]:.4f} + 0*{a1_2[1]:.4f} + 0*{a1_2[2]:.4f} = {z2_2[0]:.4f}")
print(f"   z2[1] = 0*{a1_2[0]:.4f} + 0.1*{a1_2[1]:.4f} + 1*{a1_2[2]:.4f} = {z2_2[1]:.4f}")
print(f"   a2 = ReLU([{z2_2[0]:.4f}, {z2_2[1]:.4f}]) = [{a2_2[0]:.4f}, {a2_2[1]:.4f}]")

print("\n3. Вычисление выходного слоя:")
print(f"   z3 = 0.1*{a2_2[0]:.4f} + 0.1*{a2_2[1]:.4f} = {z3_2[0]:.6f}")
print(f"   y_hat = sigmoid({z3_2[0]:.6f}) = {a3_2[0]:.6f}")

ДЕТАЛЬНЫЙ РАЗБОР ВЫЧИСЛЕНИЙ (для 2-х скрытых слоёв)

1. Вычисление первого скрытого слоя:
   z1[0] = 0.2*1 + 0*0 + 0*2 + 0*(-1) + 0*0.5 = 0.2
   z1[1] = 0*1 + 0.2*0 + 0*2 + 0*(-1) + 0*0.5 = 0.0
   z1[2] = 0*1 + 0*0 + 0.2*2 + (-0.1)*(-1) + 0*0.5 = 0.4 + 0.1 = 0.5
   a1 = tanh([0.2, 0, 0.5]) = [0.1974, 0, 0.4621]

2. Вычисление второго скрытого слоя:
   z2[0] = 0.1*0.1974 + 0*0.0000 + 0*0.4621 = 0.0197
   z2[1] = 0*0.1974 + 0.1*0.0000 + 1*0.4621 = 0.4621
   a2 = ReLU([0.0197, 0.4621]) = [0.0197, 0.4621]

3. Вычисление выходного слоя:
   z3 = 0.1*0.0197 + 0.1*0.4621 = 0.048185
   y_hat = sigmoid(0.048185) = 0.512044
